const mongoose = require('mongoose');

const ProductSchema = mongoose.Schema({
    title:{
        type:String,
    },
    description:{
        type:String,
    },
    price:{
        type:Number,
    },
    discountedprice:{
        type:Number
    },
    discountpercent:{
        type:Number
    },
    quantity:{
        type:Number
    },
    brand:{
        type:String
    },
    color:{
        type:String
    },
    sizes:[{
        name:{
            type:String,
        },
        quantity:{
            type:Number,
        }
    }],
    ImageUrl:{
        type:String,
    },
    ratings:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'ratings',
    }],
    reviews:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'reviews',
    }],
    numRatings:{
        type:Number,
        default:0
    },
    category:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'categories'
    },
    createdAt:{
        type:Date,
        default:Date.now(),
    }
})

const ProductModel = mongoose.model('products',ProductSchema);
module.exports=ProductModel;